### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by tippenein** [bitemyapp/esqueleto#1]
The Haddock documentation is [pretty good](https://hackage.haskell.org/package/esqueleto-2.4.3/docs/Database-Esqueleto.html) but the readme should include the most useful bits of these examples.

It should highlight `where_`, `sub_select`, `InnerJoin`, etc. It would also be nice to have input on common "gotcha's" and import practices in order to avoid overlap with Persistent (`import qualified Database.Esqueleto as E`).

**Comment by bitemyapp** [comment]
I actually just mentioned the Persistent/Aeson overlap on Slack. That drives me crazy. I think docs are a good short-term fix since I'd like to keep changes minimal while we get caught up on everything.

**Comment by bitemyapp** [comment]
I think this is resolved by the PR, but we should fork a couple issues from this. I'll reference this issue in them, file a more specific issue if something isn't covered.
