### ISSUE TITLE
Add UnsafeSqlFunctionArgument () instance

### ISSUE THREAD

**Issue by paf31** [bitemyapp/esqueleto#102]
This seems like it ought to be simple, right? Is there any reason I shouldn't add this?

**Comment by paf31** [comment]
I want to be able to use `unsafeSqlFunction` to give names to existing 0-argument functions.

**Comment by parsonsmatt** [comment]
That makes perfect sense. I'd be a bit concerned about possible interference with `()` being used as an actual value, but that seems really unlikely. A special type `data NoArgs = NoArgs` is a tiny bit more explicit and would definitely not have any interaction, at the cost of uglier syntax.

**Comment by bitemyapp** [comment]
> A special type `data NoArgs = NoArgs` is a tiny bit more explicit and would definitely not have any interaction, at the cost of uglier syntax.

That'd be my preference.

**Comment by parsonsmatt** [comment]
I've backtracked on this, actually - it makes more sense to have the "no argument" type be `()` in symmetry with all the other tuple-only instances.
