### ISSUE TITLE
Examples for some fundamental queries are necessary

### ISSUE THREAD

**Issue by EugineKosenko** [bitemyapp/esqueleto#103]
What is the most simple translation of the next SQL-queries to Esqueleto?

select count(*) from foo;

select title, sum(weight), "test" from foo group by title;

select f.title, count(*)
from foo f, bar b
where f.id = b.parent
group by f.title;

I hope these samples are simple enough to understand the data schema.

**Comment by bitemyapp** [comment]
>select count(*) from foo;

There's a couple examples in http://hackage.haskell.org/package/esqueleto-2.5.3/docs/Database-Esqueleto.html

>select title, sum(weight), "test" from foo group by title;

You can see how to use `sum_` in the test suite.

https://github.com/bitemyapp/esqueleto/search?q=sum_&unscoped_q=sum_

>select f.title, count(*)
>from foo f, bar b
>where f.id = b.parent
>group by f.title;

One of the main examples of `countRows` in the docs is also a `groupBy`.

**Comment by EugineKosenko** [comment]
I'm sorry, but for the very first sample the code is not so obvious. Let's consider the next variant

select $
from $ \foo -> do
return countRows

This code causes type ambiguity, and we must give to compile an advice, which table we use in this case. For now I've experimentally found the next trick:

select $
from $ \foo -> do
orderBy [asc (foo ^. FooBar)]
return countRows

In this case compiler understands, what table do I mean, but this seems dull and artifical. Is it a better way to resolve such problems?

**Comment by FintanH** [comment]
@EugineKosenko Would it not be sufficient to use `TypeApplications`?

I think something like:
```haskell
select $
from @Foo $ \_ -> do
return countRows
```

**Comment by FintanH** [comment]
Ah sorry, I was wrong here. It might have to be more like:
```haskell
[Value c2] <- select $
                     from @Topic $ \(_ :: Topic) ->
                         do
                           return countRows
```

I'll try reproduce using the example. I was mostly postulating in my suggestion :)

**Comment by EugineKosenko** [comment]
It's pity, the error message is the same:
```
test2.hs:33:22: error:
    • Couldn't match type ‘Topic’ with ‘SqlQuery’
      Expected type: SqlQuery (SqlExpr (Value Int))
        Actual type: Topic (SqlExpr (Value Int))
```
I thought, the proper code would be

```
       [Value c2] <- select $
                     from $ \(_ :: Topic) ->
                         do
                           return countRows
```

However, it also causes an error:

```
test2.hs:33:22: error:
    • No instance for (From SqlQuery SqlExpr SqlBackend Topic)
        arising from a use of ‘from’
    • In the second argument of ‘($)’, namely

```

**Comment by EugineKosenko** [comment]
As for my third sample, I have the next real case:

```
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}

import Database.Persist.TH
import Database.Persist.Sqlite(runSqlite, runMigration)
import Database.Esqueleto
import Control.Monad.IO.Class

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Topic
   title String
   quoteId QuoteId
Quote
   text String
|]

main :: IO ()
main = do
  runSqlite "test.sqlite" $ do
       runMigration migrateAll
       ts1 <- select $
              from $ \(q, t) -> do
                where_ (q ^. QuoteId ==. t ^. TopicQuoteId)
                return (t ^. TopicTitle)
       liftIO $ mapM_ (putStrLn . show) ts1

       ts2 <- select $
              from $ \(q, t) -> do
                where_ (q ^. QuoteId ==. t ^. TopicQuoteId)
                groupBy (t ^. TopicTitle)
                return (t ^. TopicTitle, countRows)
       liftIO $ mapM_ (putStrLn . show) ts2

```

The first snippet is compiled and works, but the second causes the error:

```
test.hs:33:15: error:
    • Ambiguous type variables ‘expr0’, ‘a0’, ‘rb’ arising from a use of ‘select’
      prevents the constraint ‘(Database.Esqueleto.Internal.Sql.SqlSelect
                                  (expr0 (Value a0)) rb)’ from being solved.
      Probable fix: use a type annotation to specify what ‘expr0’, ‘a0’, ‘rb’ should be.
```
Once I'd resolved the problem with the "orderBy" workaround, but now it doesn't work again...

**Comment by FintanH** [comment]
@EugineKosenko Found the correct annotation for you:

```haskell
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE ScopedTypeVariables        #-}
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE TypeApplications           #-}
{-# LANGUAGE TypeFamilies               #-}

module Main where

import Database.Persist.TH
import Database.Persist.Sqlite hiding ((==.), count)
import Database.Esqueleto
import Control.Monad.IO.Class

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Topic
   title String
|]

main :: IO ()
main = do
  runSqlite "test.sqlite" $ do
       runMigration migrateAll
       [Value c1] <- select $
                     from $ \t ->
                         do
                           orderBy [asc (t ^. TopicTitle)]
                           return countRows
       liftIO $ putStrLn $ show (c1 :: Int)

       [Value c2] <- select $
                     from $ \(_ :: SqlExpr (Entity Topic)) ->
                         do
                           return countRows
       liftIO $ putStrLn $ show (c2 :: Int)
```

`from`'s type is `from :: From query expr backend a => (a -> query b) -> query b` so I thought at first that the `a` there should be `Topic`, but it turns out it was actually supposed to be `SqlExpr (Entity Topic)`. fwiw, I found this out by finding the `count` used here https://hackage.haskell.org/package/esqueleto-2.5.3/docs/Database-Esqueleto.html#v:case_ and then playing around with that and type annotating the expressions.

**Comment by EugineKosenko** [comment]
Great! Thank you for the help!

Can you help me with groupBy in my second case? I suspect, the proper solution in that case will be the same, because I'd fixed it once with the same workaround. I'll try, but you help may increase my investigations.

Thanks in advance!

**Comment by FintanH** [comment]
Unfortunately in the second case the compiler is having a hard time finding out what the `Num a` should be for the result of `countRows`. So one way is to pull this out into a top level function or, as I did, type annotate during the printing:

```haskell
ts2 <- select $
        from $ \(q, t) -> do
          where_ (q ^. QuoteId ==. t ^. TopicQuoteId)
          groupBy (t ^. TopicTitle)
          return (t ^. TopicTitle, countRows)
liftIO $ mapM_ (\(Value t, Value (c :: Int)) -> print (t, c)) ts2
```

**Comment by EugineKosenko** [comment]
Ok, it works too. I suspected something like this, but you showed me the shortest solution.

I have no more questions. Big thanks!

**Comment by FintanH** [comment]
Happy to help :)
