### ISSUE TITLE
Building haddock for ghc-8.4+ is broken

### ISSUE THREAD

**Issue by brandon-leapyear** [bitemyapp/esqueleto#110]
```
$ cat .stack-work/logs/esqueleto-2.6.0.log
Configuring esqueleto-2.6.0...
Preprocessing library for esqueleto-2.6.0..
Building library for esqueleto-2.6.0..
Preprocessing library for esqueleto-2.6.0..
Running Haddock on library for esqueleto-2.6.0..
Haddock coverage:
haddock: internal error: internal: extractDecl
CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1116:12 in main:Haddock.Interface.Create
```

This is broken both in `lts-12.24` and `lts-13.0`. It's probably a haddock bug, but I can't figure out why it's happening.

I suspect it has something to do with selectively exporting functions from [`Esqueleto`](https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto.hs#L41), but I don't know for sure.

**Comment by brandon-leapyear** [comment]
I added debug code and got:
```
haddock: panic! (the 'impossible' happened)
  (GHC version 8.4.4 for x86_64-apple-darwin):
	extractDecl

Unhandled decl for SqlBackendKey:
    data family BackendKey backend :: *
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
      pprPanic, called at src/Haddock/Interface/Create.hs:1100:12 in haddock-api-2.20.0-9FnywoxlUeu2IGqOI4hPVv:Haddock.Interface.Create
```
So this could be a bug in haddock/persistent

**Comment by bitemyapp** [comment]
I don't think this is in our wheelhouse. I'm closing for now, re-open if I misunderstood or you learn something new.

**Comment by parsonsmatt** [comment]
unfortunately I believe this will block putting `esqueleto` back on Stackage. I'm reopening

**Comment by FintanH** [comment]
Is this causing the docs to not appear on Hackage? http://hackage.haskell.org/package/esqueleto-2.6.1/docs/Database-Esqueleto.html

![image](https://user-images.githubusercontent.com/3503528/53802936-16d21d80-3f3b-11e9-935a-c342ce767061.png)

**Comment by parsonsmatt** [comment]
hmmm, I thought that this was going to be fixed by #114.

**Comment by parsonsmatt** [comment]
Docs are up for the latest veresion of esqueleto.

To get docs for previous versions, it's necessary to build Haddock from source from the commit with the patch. It was never released. I went down a bit of a rabbit hole and decided against pursuing docs for 2.6.1 as 2.7.0 is up.

**Comment by friedbrice** [comment]
I just noticed the problem using stack resolver lts-13.1, (GHC 8.6.3, Haddock 2.22.0, Esqueleto 2.6)

```
--  While building package esqueleto-2.6.0 using:
      /home/daniel/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 haddock --html --hoogle --html-location=../$pkg-$version/ --haddock-option=--quickjump
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/daniel/lumihq/lumi/powerpuff/.stack-work/logs/esqueleto-2.6.0.log

    Preprocessing library for esqueleto-2.6.0..
    Building library for esqueleto-2.6.0..
    Preprocessing library for esqueleto-2.6.0..
    Running Haddock on library for esqueleto-2.6.0..
    Haddock coverage:
    haddock: internal error: internal: extractDecl
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1116:12 in main:Haddock.Interface.Create
```

Is there a way to locally build docs for 2.6?
