### ISSUE TITLE
Postgres JSON joining

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#121]
If you've got non-trivial JSON in your codebase, it is common to want to `JOIN` against it.

```sql
SELECT foo.id, array_vals.blah
FROM foo
CROSS JOIN jsonb_array_elements(foo.jsonb_col -> 'json_array') AS array_vals
WHERE foo.id = 3
```

This isn't currently possible with `esqueleto` as far as I can tell.

**Comment by parsonsmatt** [comment]
```
select $
from $ \foo -> do
vals <- crossJoinJsonArrayElements (foo ^. FooJsonBCol |-> val "json_array")
where_ (foo ^. FooId ==. val 3)
pure (foo ^. FooId, vals)
```

With an operator like `(|->) :: SqlExpr Aeson.Value -> SqlExpr (Value Text) -> SqlExpr Aeson.Value`, that gives a signature like:

```
crossJoinJsonArrayElements :: SqlExpr Value -> SqlQuery (SqlExpr Value)
```

and would need to generate SQL like:

```
CROSS JOIN json_b_array_elements( splice the field in here )
```

**Comment by bitemyapp** [comment]
@parsonsmatt just wondering off-hand, not as evaluation criteria for the feature: how fast is that?

**Comment by parsonsmatt** [comment]
I don't have anything to test/measure/compare it against. I suspect that it is not as fast as a properly normalized database would be with real joins.

**Comment by Vlix** [comment]
Is this now possible with `esqueleto-3.1.0`?

**Comment by parsonsmatt** [comment]
With the experimental machinery, this can be done:

```haskell
fromJsonbArrayElements :: (ToJSON a, FromJSON a) => SqlExpr (Value (Jsonb [a])) -> SqlQuery (SqlExpr (Value (Jsonb a)))
fromJsonbArrayElements valarray =
    Experimental.from $ Experimental.SubQuery $ pure $ jsonbArrayElements valarray
  where
    jsonbArrayElements :: SqlExpr (Value (Jsonb [a])) -> SqlExpr (Value (Jsonb a))
    jsonbArrayElements = unsafeSqlFunction "jsonb_array_elements"
```

And it even works in sub-selects!

```haskell
          selectRethrowingQuery $ do
            t <-
              from $
                Table @TaxRates
            pure (t, subSelect $ do
              jv <- fromJsonbArrayElements (t ^. TaxRatesValue)
              pure jv)
```

But it doesn't work if you try to summon both of them up.

```haskell
        res <-
          selectRethrowingQuery $ do
            t <- from $ Table @TaxRates
            jv <- fromJsonbArrayElements (t ^. TaxRatesValue)
            pure (t, jv)
```

This returns the query

```
SELECT "tax_rates_singleton"."id", "tax_rates_singleton"."value", "q"."v"
FROM "tax_rates_singleton", (SELECT jsonb_array_elements("tax_rates_singleton"."value") AS "v"
) AS "q"

SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = 
"invalid reference to FROM-clause entry for table \"tax_rates_singleton\"", sqlErrorDetail = "", sqlErrorHint = "There is an entry for table \"tax_rates_singleton\", but it cannot be referenced from this part of the query."})
```

I thought about using eg `CrossJoin` in the corresponding from clause:

```haskell
from $
  Table @TaxRates
  `CrossJoin`
  SubQuery (fromJsonbArrayElements ...)
```

But the `t :: SqlExpr (Entity TaxRates)` value isn't in scope here. We'd need to bring it into scope somehow.

Hm.

**Comment by parsonsmatt** [comment]
Yo @belevy I think that `SubQuery` should be a function, like the join types. That would let us write something like:

```
from $ Table @Foo
  `CrossJoin` SubQueryWith (\foo -> ...)
```

:thinking: Any idea on how this might work?

**Comment by belevy** [comment]
what you are trying to do is a LATERAL cross join. I have wanted to implement something like LateralQuery (\x -> ) where the x is whatever has been put into scope. The implicit CrossJoin caused by pulling two from clauses into the SqlQuery should probably enforce LATERAL not sure if that works with the comma syntax though.

**Comment by belevy** [comment]
Ok its not the prettiest thing but it at least mostly works. Maybe you can take a look and make it work more? https://github.com/belevy/esqueleto/tree/lateral-joins
