### ISSUE TITLE
Throw errors at compile time instead of runtime

### ISSUE THREAD

**Issue by ibarrae** [bitemyapp/esqueleto#135]
In the module `Database.Esqueleto.Internal.Internal` it throws `CompositeKeyError` and `SqlBinOpCompositeError` when forming queries. I was wondering if it would be possible/makes sense to throw errors with [TypeError](https://hackage.haskell.org/package/base-4.12.0.0/docs/src/GHC.TypeLits.html#TypeError)? I think that would be great to save some time and don't wait for executing a real query on the DB.

**Comment by bitemyapp** [comment]
@ibarrae it's probably more involved than you're imagining at the moment. `TypeError` is something you incorporate into constraint solving, be it a type family or a type class instance. You can't turn an arbitrary pattern match at runtime into a `TypeError` so far as I'm aware.

Getting rid of the partiality in Esqueleto is one of my long-term design goals, but I don't think there's a piecemeal solution. The underlying representation needs housecleaning.

If you can make this idea work, I'd absolutely love to see it in a PR.

**Comment by ibarrae** [comment]
Thanks for the clarification @bitemyapp :tada:
