### ISSUE TITLE
Counting rows in a table without a `where_` clause

### ISSUE THREAD

**Issue by erikd** [bitemyapp/esqueleto#136]
I would like to count the rows in a table. With an older version of Esqeleto` I used to be able to do:
```
queryXCount :: MonadIO m => ReaderT SqlBackend m Word
queryXCount = do
  res <- select . from $ \ (__:: X) -> do
            pure countRows
  pure $ maybe 0 unValue (listToMaybe res)
```
but now that gives me a error:
```
    • Could not deduce (From X) arising from a use of ‘from’
```
I can't added the `From X` constraint to the function then the function that calls that has to satisfy the constraint.

Is there a nice easy way around this?

**Comment by erikd** [comment]
I can satisfy the constraint by using a dumb and obvious:
```
            where_ (x ^.XId ==. x ^.XId)
```
but that feels rather unsatisfying.

**Comment by parsonsmatt** [comment]
I think you need `_ :: SqlExpr (Entity X)` instead of `_ :: X`.

**Comment by erikd** [comment]
Thanks @parsonsmat! That fixed it.
