### ISSUE TITLE
Add esqueleto to the stackage

### ISSUE THREAD

**Issue by kseo** [bitemyapp/esqueleto#15]
Adding esqueleto to the stackage would be convenient for users. 

https://github.com/fpco/stackage/#add-your-package

**Comment by qrilka** [comment]
It's on stackage https://www.stackage.org/package/esqueleto but a bit outdated

**Comment by bitemyapp** [comment]
I have an issue up for getting Esqueleto back in Stackage:

https://github.com/fpco/stackage/pull/2191

I need to follow up on getting this: https://github.com/bitemyapp/esqueleto/pull/12 released on Hackage and then we'll see how it shakes out.

**Comment by bitemyapp** [comment]
Closing this, follow the fpco ticket if you want to watch this.
