### ISSUE TITLE
*OuterJoin constructors should enforce nullability

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#150]
We're running into a few bugs at work now where someone did:

```haskell
select $
from $ \(a `LeftOuterJoin` b) -> do
where_ (a ^. AField ==. b ^. BField)
pure (a, b ^. BOtherField)
```

and we get `PersistMarshallException` trying to parse the `null` value out. These should be enforced to be a `Maybe`.

**Comment by belevy** [comment]
Fixed in #172
