### ISSUE TITLE
Add UnsafeSqlFunctionArgument instances for bigger tuples?

### ISSUE THREAD

**Issue by hdgarrood** [bitemyapp/esqueleto#162]
At the moment, the `UnsafeSqlFunctionArgument` instances only support sql functions of up to 4 arguments. However, there are functions you might want to call which accept more than 4 arguments. For example: postgres' `make_interval`, which takes 7 (documented at https://www.postgresql.org/docs/10/functions-datetime.html). Would a PR adding instances for functions with up to 7 (or perhaps more) arguments be considered?

**Comment by parsonsmatt** [comment]
yup!
