### ISSUE TITLE
Add `+ interval 'amount "value"` operator for PostgreSQL

### ISSUE THREAD

**Issue by ibarrae** [bitemyapp/esqueleto#169]
Hey folks, would it make sense to add `+ interval 'amount "type"'` to date/times like this to PostgreSQL functions?
```sql
select date('01-01-1992') + interval '5 weeks' as result;
       result        
---------------------
 1992-02-05 00:00:00
```

If that's the case, I'm more than happy to help with it :smile:

**Comment by bitemyapp** [comment]
I think we have `+` don't we? Do you mean to ask if we should add `interval`? /cc @parsonsmatt

**Comment by bitemyapp** [comment]
Yeah `+` is in there:

```haskell
(+.)  :: PersistField a => SqlExpr (Value a) -> SqlExpr (Value a) -> SqlExpr (Value a)
(+.)  = unsafeSqlBinOp " + "
```

**Comment by bitemyapp** [comment]
If you need `interval` for a project, I recommend adding it to a fork of Esqueleto, depending on that fork, adding it, then testing it with your project. Once you've done that you could upstream it. Does that make sense?

**Comment by ibarrae** [comment]
Sure, that makes sense @bitemyapp. I did mean to add `interval` to the PostgreSQL module. I'll work on it and push a PR in the upcoming days and thanks :smile:

**Comment by ibarrae** [comment]
I think this is no longer necessary since this [PR](https://github.com/yesodweb/persistent/pull/1053) was merged on persistent. Do you agree @bitemyapp?

**Comment by parsonsmatt** [comment]
You'd need an `intervalToDate :: SqlExpr (Value Interval) -> SqlExpr (Value UTCTime)` so that the types work out. `(+.)` requires that both arguments have the same type.

It'd be easiest to write:

```haskell
addInterval :: SqlExpr (Value UTCTime) -> SqlExpr (Value Interval) -> SqlExpr (Value UTCTIme)
addInterval t i = t +. i'
  where
    i' :: SqlExpr (Value UTCTime)
    i' = veryUnsafeCoerceSqlExprValue i
```

**Comment by ibarrae** [comment]
Cool thanks for the answer @parsonsmatt, I think that solves all my doubts. I think we can close this :smile:
