### ISSUE TITLE
Extend the Postgres module with `@>` and `&&` Array operators

### ISSUE THREAD

**Issue by ChrisCoffey** [bitemyapp/esqueleto#17]
It would be great to add support for some of the most common PSQL array operations, contains & overlap. 

I'm happy to submit the PR if you think Esqueleto's `PostgreSQL` module is a good place for them.

**Comment by parsonsmatt** [comment]
This would be great!

We already have these operators in he `PostgreSQL.JSON` module, so a new module `Database.Esqueleto.PostgreSQL.Array` would be the logical place for them to live.

**Comment by Vlix** [comment]
I believe this is done with my contribution last year?

**Comment by Vlix** [comment]
Oh, has the title changed? Because I don't believe my statement is correct in this case 🤔 
We'd need an extra `Database.Esqueleto.PostgreSQL.Array` module for operators specific to arrays for this.
