### ISSUE TITLE
DeconstructionError when using primary key that wraps a primary key on another table

### ISSUE THREAD

**Issue by MaxGabriel** [bitemyapp/esqueleto#176]
Hi, I think there's a bug with using a primary key on a table, that is itself wrapping a primary key on another table. As an example, here ArticleMetadata's primary key is an `ArticleId`, which is the primary key of `Article`.

```
  Article
    title String
    frontcoverNumber Int
    Foreign Frontcover fkfrontcover frontcoverNumber
    deriving Eq Show
  ArticleMetadata
    articleId ArticleId
    Primary articleId
    deriving Show
```

In this case, an esqueleto query that does `(val articleMetadataId)` will error with `SqlBinOpCompositeErr DeconstructionError`.

I added a test to demonstrate this here:

https://github.com/MercuryTechnologies/esqueleto/compare/master...MaxGabriel:primaryForeignKeyBug?expand=1

I also added a `Text` field to `DeconstructionError` to get a little more data. The test fails with this:

```
  test/Common/Test.hs:760:5:
  1) Tests that are common to all backends, select:JOIN, allows using a primary key that is itself a key of another table
       uncaught exception: EsqueletoError
       SqlBinOpCompositeErr (DeconstructionError "(\"?\",[PersistInt64 16])")
```

This appears to be the code throwing, modified to show the bad value from deconstruct:

```
    deconstruct :: (TLB.Builder, [PersistValue]) -> ([TLB.Builder], [PersistValue])
    deconstruct ("?", [PersistList vals]) = (replicate (length vals) "?", vals)
    deconstruct (b', []) = (TLB.fromLazyText <$> TL.splitOn "," (TLB.toLazyText b'), [])
    deconstruct bad = throw (SqlBinOpCompositeErr (DeconstructionError (T.pack $ show bad)))
```

Questions I have:

1. Does this seem like a bug to you? I think this is valid use of persistent/esqueleto but wanted to just double check
2. Any ideas how to handle this case?
3. ~Any ideas on a workaround?~ (Edit: found: use `in_` and `valList` with a single value)
4. Related, I think it would be nice give a more detailed error when deconstruction fails. Would it be reasonable to add a string or text argument to `DeconstructionError` so if this happens in the future, it can be debugged more easily? It looks to be from an internal module so it seems fine to add it even though it's a "breaking" change. If so my branch adds this, and I could improve the error message to be more clear.

https://github.com/bitemyapp/esqueleto/issues/36 is possibly related?

**Comment by MaxGabriel** [comment]
Possibly https://hackage.haskell.org/package/esqueleto-3.3.1.1/docs/Database-Esqueleto.html#v:toBaseId could workaround this?

**Comment by MaxGabriel** [comment]
Update: found a workaround. Instead of:

```
where_ $ (articleMetadata ^. ArticleMetadataId) ==. (val ((ArticleMetadataKey articleId)))
```

You can do:

```
where_ $ (articleMetadata ^. ArticleMetadataId) in_ (valList [(ArticleMetadataKey articleId)])
```

**Comment by belevy** [comment]
Why bother wrapping the article id in `ArticleMetadataKey`? 
Could you not just check the article id directly:
```
where_ $ articleMetadata ^. ArticleMetadataArticleId ==. val articleId
``` 

I agree that it probably shouldn't have a runtime error though but it seems like your proposed workaround is more complicated than necessary.

**Comment by MaxGabriel** [comment]
My workaround is just the first thing I came up with, yours is definitely simpler. Regardless, agree it’s a bug and nice fix!
