### ISSUE TITLE
[Question] subquery as field in select

### ISSUE THREAD

**Issue by shineli-da** [bitemyapp/esqueleto#188]
Is it possible to translate subquery as field in select like below into esqueleto?
```
SELECT
	(
	SELECT
		avg( t1.b ) 
	FROM
		( SELECT * FROM t LIMIT 100 ) AS t1 
	WHERE
		t1.a = t2.a 
	) 
FROM
	t2
```

**Comment by parsonsmatt** [comment]
Yes. Using the new Experimental module, we can write:

```haskell
import Database.Esqueleto hiding (from, on)
import Database.Esqueleto.Experimental

query =
    select $ do
        t2 <- from $ Table @T2
        pure $ subSelect $ do
            t1 <- from $ SelectQuery $ do
                t <- from $ Table @T
                limit 100
                pure t
            where_ $ t1 ^. TA ==. t2 ^. T2A
            pure $ avg_ (t1 ^. TB)
```

This uses two features of `esqueleto`:

The `subSelect` family of functions, which are useful whenever you want to use a subquery as a value.

The `SelectQuery` combinator, which allows you to use a subquery in a `FROM` clause.

**Comment by shineli-da** [comment]
What I got from using `subSelect` with `SelectQuery` is an error:
`src/Database/Esqueleto/Internal/Internal.hs:2197:28-48: Non-exhaustive patterns in lambda`

**Comment by shineli-da** [comment]
This is what I got by following the above. Any suggestions?
```
src/Database/Esqueleto/Internal/Internal.hs:2197:28-48: Non-exhaustive patterns in lambda
```

**Comment by parsonsmatt** [comment]
@belevy gonna tag you in on this, any idea what's going on? Relevant code is:

```haskell
-- | (Internal) A raw SQL function.  Once again, the same warning
-- from 'unsafeSqlBinOp' applies to this function as well.
unsafeSqlFunction :: UnsafeSqlFunctionArgument a =>
                     TLB.Builder -> a -> SqlExpr (Value b)
unsafeSqlFunction name arg =
  ERaw Never $ \info ->
    let (argsTLB, argsVals) =
          uncommas' $ map (\(ERaw _ f) -> f info) $ toArgList arg
    in (name <> parens argsTLB, argsVals)
```

**Comment by belevy** [comment]
Yah EAliasedValue isn't being handled in that lambda. I'll take a look and try to make a patch today.

**Comment by shineli-da** [comment]
Just reporting back. The PR above works for me. Thanks.
