### ISSUE TITLE
Add support for INTERSECT, UNION, UNION ALL and EXCEPT operators

### ISSUE THREAD

**Issue by olynch** [bitemyapp/esqueleto#19]
The SQL standard has support for adding together the results of various SELECT statements by computing their union, intersection or difference. As far as I can tell, esqueleto doesn't have parts in its DSL to support this. I am not familiar enough with the source to write a patch myself, but if I end up getting something working in my app I will comment again with how I managed to do it.

**Comment by mpodlasin** [comment]
I would be very interesed in this. How hard would it be to implement for someone who is not familiar with the source? Are there any good/similar enough operators to follow when writing an implementation?

**Comment by FintanH** [comment]
@bitemyapp I guess this is relevant to https://github.com/bitemyapp/esqueleto/issues/50 as well

**Comment by parsonsmatt** [comment]
Fixed by #172
