### ISSUE TITLE
Experimental: Union of queries with limit doesn't render properly

### ISSUE THREAD

**Issue by googleson78** [bitemyapp/esqueleto#194]
In mysql at least, when the queries being `UNION`'d have `LIMIT`s in them, you need extra parens around each subquery

**Comment by belevy** [comment]
This is not standard sql behaviour. MySQL is the only engine I know that allows parentheses and limits/orderby. I do wonder if maybe we could do a check to see if limit and orderby are used in the queries being unioned and optionally wrap them

**Comment by googleson78** [comment]
Could you elaborate on the first part? I'm an SQL newbie, is there some issue with just putting extra parens around `x` and `y` in this expression: 
```sql
x `UNION` y
```

It seems to me like redundant parens shouldn't invalidate the query (?)

wrt. the check, I remember spotting some `NeedParens` datatype and mechanism in `SqlExpr` for this purpose, perhaps it could be helpful here? (although `Experimental.from` directly generates `SqlQuery`s)

(and thanks for making `Experimental` and responding so fast! the `JOIN`s seem great, and I would've had to write raw sql for the union otherwise!)

**Comment by belevy** [comment]
Yah, this isn't the only case of extra parentheses causing the sql engine to choke. For example `value in ((1,2,3))` is a sql error. MySQL is fine with parens in set operations but at least sqlite isn't and I'm fairly sure that postgres also doesn't like it.

**Comment by googleson78** [comment]
In this case the issue is much worse, I think. I'm pretty sure at the moment of rendering `esqueleto` isn't aware of the backend being used. I'm not sure what the solution here is at all :/ 
* some way to plug this info (or "information on how to render unions") somewhere (?)
* creating some kind of separate version of `Experimental.from` for mysql in the mysql specific module

@parsonsmatt any clues?

**Comment by parsonsmatt** [comment]
Supporting MySQL is *the worst* :joy: 

We can know via [`connRDBMS`](https://www.stackage.org/haddock/lts-16.4/persistent-2.10.5.2/Database-Persist-Sql.html#t:SqlBackend), and I think the `SqlBackend` is carried around in the `SqlQuery` monad.
