### ISSUE TITLE
No docs for 3.3.4.0 on Hackage

### ISSUE THREAD

**Issue by googleson78** [bitemyapp/esqueleto#207]
There are no docs for esqueleto 3.3.4.0 on Hackage - https://hackage.haskell.org/package/esqueleto-3.3.4.0

Is this the right place to be reporting this? Sorry if it isn't!

**Comment by jkachmar** [comment]
Looks like Hackage doesn’t provide any additional context as to why Haddock generation failed:

https://hackage.haskell.org/package/esqueleto-3.3.4.0/reports/3

**Comment by googleson78** [comment]
It generates haddock fine locally with cabal too :thinking:

**Comment by belevy** [comment]
This appears to have been caused by the re-export of `Database.Esqueleto` from `Database.Esqueleto.Experimental`. This is fixed by #215 though 3.3.4.0 will not have docs in that case.
