### ISSUE TITLE
[Experimental] Raw Subquery in FROM

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#209]
It'd be nice to be able to write, eg:

```haskell
select $ do
  a :& b :& c <-
    from $
      Table @A 
      `InnerJoin` 
      Table @B 
        `on` do
          \(a :& b) -> ...
      `InnerJoin`
      RawQuery @C rawQuery
        `on` do
          \(_ :& b :& c) -> do
            ....
  ...

rawQuery = [st|
WITH RECURSIVE children AS (
    SELECT c.*
    FROM component AS c
    WHERE c.id = #{bikeId}

    UNION

    SELECT c_r.*
    FROM component AS c_r
    INNER JOIN children AS c
        ON c.id = c_r.parent
    )
SELECT ??
FROM children AS component
    |]
|]
```

The resulting SQL would be like

```sql
SELECT * 
FROM a
INNER JOIN b
  ON ...
INNER JOIN (
  WITH RECURSIVE children AS (
    SELECT c.*
    FROM component AS c
    WHERE c.id = #{bikeId}

    UNION

    SELECT c_r.*
    FROM component AS c_r
    INNER JOIN children AS c
        ON c.id = c_r.parent
    )
SELECT ??
FROM children AS component
)
```

**Comment by charukiewicz** [comment]
Great idea. @parsonsmatt which package/module are you using for the text quasi-quoter to construct the query with interpolated values? Is it `st` from [`Text.Shakespeare.Text`](https://hackage.haskell.org/package/shakespeare-2.0.25/docs/Text-Shakespeare-Text.html)?

**Comment by parsonsmatt** [comment]
Yup! A specialized QQ that could parse Esqueleto/Persistent stuff (like the `Database.Persist.QQ` one) could be neat too.

**Comment by belevy** [comment]
Ultimately id like to see something like `with :: CTE a -> (SqlExpr a -> SqlQuery b) -> SqlQuery b`. 

Either way a raw query escape hatch is probably a decent idea so that you don't have to completely abandon esqueleto to write your query if there is a feature that is yet to be supported.

**Comment by parsonsmatt** [comment]
Going to close this out since the features were implemented properly.
