### ISSUE TITLE
Recommend HLint rule disallowing `==. nothing`?

### ISSUE THREAD

**Issue by amitojps** [bitemyapp/esqueleto#210]
My dear coworker @MaxGabriel has previously added documentation to `isNothing` detailing that `isNothing x` is almost always to be used over `x ==. nothing`, because equality comparisons with `NULL` will return `NULL`, rather than `true` or `false`.  See https://github.com/bitemyapp/esqueleto/pull/203

We have an HLint rule that prevents people from making this mistake:
```
- error: {lhs: v ==. nothing, rhs: Database.Esqueleto.isNothing v, name: Use Esqueleto's isNothing}
```

What about adding a recommendation to use this hint to the documentation? I know not everyone uses HLint, but I think something like "If you use HLint, you can include the following hint to error if you make this mistake..." in the `isNothing` documentation would be fairly useful at a fairly low cost. Happy to PR this if there's interest!

**Comment by MaxGabriel** [comment]
```yaml
- error: {lhs: v ==. nothing, rhs: Database.Esqueleto.isNothing v, name: Use Esqueleto's isNothing}
- error: {lhs: v ==. val Nothing, rhs: Database.Esqueleto.isNothing v, name: Use Esqueleto's isNothing}
- error: {lhs: v !=. nothing, rhs: not_ (Database.Esqueleto.isNothing v), name: Use Esqueleto's not isNothing}
- error: {lhs: v !=. val Nothing, rhs: not_ (Database.Esqueleto.isNothing v), name: Use Esqueleto's not isNothing}
```

We've expanded to these 4 rules ^
