### ISSUE TITLE
Runtime error with subqueries

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#216]
I had a subquery for a join table:

```haskell
joinTable :: SqlQuery (SqlExpr (Entity A), SqlExpr (Entity B))
joinTable = fmap (\(a :& _ :& b) -> (a, b)) $
  from $
    Table @A
    `InnerJoin`
    Table @JoinAB
      `on` do 
        \(a :& jab) -> a ^. AId ==. jab ^. JoinABAId
    `InnerJoin`
    Table @B
      `on` do
        \(_ :& jab :& b) -> jab ^. JoinABBId ==. b ^. BId
```

This compiles fine, but it fails in odd places.

If I write `(a, b) <- joinTable`, it's fine, provided I don't actually do *anything* with it. If I so much as throw a `limit 1`, then I get another error.

If I write `(a, b) <- from $ SubQuery joinTable`, then it fails with `SqlBinOpCompositeErr DeconstructionError` - a run-time error.

If I use `:&` instead of `(,)` then I get a lot of compile-errors.

Doing ongoing research on this...

**Comment by belevy** [comment]
This is in v3.3.4.0? If you could tell my what postgresql is barfing on it might explain what's malformed.

**Comment by parsonsmatt** [comment]
oh lol yeah i'm not on 3.3.4.0 let me try that
