### ISSUE TITLE
Common Table Expressions: ex WITH ... AS ... RETURNING ...

### ISSUE THREAD

**Issue by freckletonj** [bitemyapp/esqueleto#22]
Feature request!

https://www.postgresql.org/docs/current/static/queries-with.html#QUERIES-WITH-MODIFYING

My first use case I ran into was when I wanted to maintain separate Login and User tables. Login has a foreign key to User, and when I create a new Login, it needs a User to exist first, and it would be nice to issue these in one transaction.

I'd love to commit a PR when I'm better at Haskell, otherwise if it's simple for someone else, seems useful :)

**Comment by bitemyapp** [comment]
@freckletonj that sounds a lot more complicated than running a single transaction.

http://www.yesodweb.com/book/persistent

ctrl-f "single transaction"

**Comment by bitemyapp** [comment]
Closing, unlikely to do this without a good reason put forward.
