### ISSUE TITLE
Could not find module ‘Database.Esqueleto’

### ISSUE THREAD

**Issue by Ulrar** [bitemyapp/esqueleto#23]
Hi,

I'm using Persistent already in my Yesod project and it works fine.
I need to do a DISTINCT so I'm trying to use Esqueleto, but I always end up with 
> Could not find module ‘Database.Esqueleto’
I don't remember ever having that problem in previous projects using it.
Any idea what I am missing ? I've tried adding esqueleto to the cabal file but that's not apparently valid.

Thanks

**Comment by bitemyapp** [comment]
I can't help you unless you post a repro.

**Comment by bitemyapp** [comment]
Closing as I don't have any reason to believe the library is at fault here.
