### ISSUE TITLE
'undefined' with joins in Experimental syntax

### ISSUE THREAD

**Issue by arthurxavierx** [bitemyapp/esqueleto#241]
The following query produces an `undefined` error when run:
```haskell
foo :: SqlQuery (SqlExpr (Maybe (Entity Foo)), SqlExpr (Maybe (Entity Bar)))
foo = from $ Table @Foo `FullOuterJoin` Table @Bar `on` (\_ -> val False)
```

The error points to https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto/Experimental.hs#L770

I believe the problem is due to the use of a tuple instead of `:&`, as it was fixed by changing the type of the expression to `SqlQuery (SqlExpr (Maybe (Entity Foo)) :& SqlExpr (Maybe (Entity Bar)))`.

I suspect this also happens to other types of joins, not only to `FullOuterJoin`, but I have not yet tested it.

**Comment by belevy** [comment]
this should be fixed in https://github.com/bitemyapp/esqueleto/pull/228 when i get around to finishing it

**Comment by arthurxavierx** [comment]
@belevy thanks for doing god's work in that PR, it's looking absolutely fantastic!! Looking forward to having it :)
