### ISSUE TITLE
Add pgcrypto functions 

### ISSUE THREAD

**Issue by 3kyro** [bitemyapp/esqueleto#256]
Hi, I have a local implementation of the following functions from the [pgcrypto](https://www.postgresql.org/docs/8.3/pgcrypto.html) module:

```` haskell
toCrypt :: SqlString s => Algorithm -> s -> SqlExpr (Value s)
fromCrypt :: SqlString s => SqlExpr (Value s) -> s -> SqlExpr (Value Bool)
````
Usage with a contrived example would be:

```` haskell
-- insert a User
insertSelect $
    User
      <# val "new_user"
      <&> toCrypt BF "1234Password"
      -- etc

-- validate a User
select $ do
    user <- from $ Table @User
    where_ $ user ^. UserName ==. val "new_user"
      &&. fromCrypt (user ^. UserPassword) "1234Password"
    pure user
````
I was wondering if they can be included in *esqueleto* - in the PostgreSQL module - or it's better of to create an external library. 

If inclusion to *esqueleto* is OK I'd happily submit a PR

**Comment by 3kyro** [comment]
Actually going through #228, I'll wait for it to drop since I am pattern matching against the ``SqlExpr`` constructors.

**Comment by belevy** [comment]
@3kyro sorry about the change causing rework on your side. Id be happy to see a PR for the crypto functions.

**Comment by 3kyro** [comment]
@belevy No problem at all. Thanks for the confirmation, I'll submit a PR for this shortly

**Comment by 3kyro** [comment]
I'm closing this issue as there was no agreement on the proposed API.
