### ISSUE TITLE
Add `selectFirst` Esqueleto variant

### ISSUE THREAD

**Issue by ibarrae** [bitemyapp/esqueleto#257]
`esqueleto` re-exports the function [selectFirst](https://hackage.haskell.org/package/persistent-2.13.0.2/docs/Database-Persist-Class-PersistQuery.html#v:selectFirst) from `persistent` at the moment, I was wondering if a new function with similar functionality could be introduced. I've seen scenarios in which we only want 1 result or nothing from different queries. Probably doing something similar to the following:

``` haskell
fmap listToMaybe <$>
  E.select $
    E.from $ \table ->
      E.where_ $ ...
      E.limit 1
     return table
```

Something I have in mind (that I'm not even sure it compiles) would be something like the following:
``` haskell
selectFirst :: (SqlSelect a r, MonadIO m) => SqlQuery a -> SqlReadT m (Maybe r)
selectFirst query = do
    limit 1
    select query
````

I wonder if that's possible in `esqueleto`, probably would require some `lifting` though :disappointed_relieved:. I hope all of these makes sense and thanks for the great library!

**Comment by parsonsmatt** [comment]
Yeah! The code would look like: `selectFirst query = fmap listToMaybe $ select $ limit 1 >> query`  or something similar, but that is totally doable.

Maybe worthwhile to do in the 3.5 switchover.

**Comment by ibarrae** [comment]
Great, thanks for the quick reply @parsonsmatt, I'll wait for `3.5` to be merged and probably will work on those changes :tada:
