### ISSUE TITLE
tried to use `date_trunc` in postgres, but it messes up UTC times

### ISSUE THREAD

**Issue by silky** [bitemyapp/esqueleto#27]
i wrote the following

````
truncateDate 
    :: E.SqlExpr (E.Value String)  -- ^ .e.g (val "day")
    -> E.SqlExpr (E.Value UTCTime) -- ^ input field
    -> E.SqlExpr (E.Value UTCTime) -- ^ truncated date
truncateDate datePart expr = unsafeSqlFunction "date_trunc" (datePart, expr)
````

but it seems to lose some kind of UTC magic.

if i use this, then in postgres  times like `2017-04-16 16:37:32.090688+10` become `2017-04-16 00:00:00+10` and when i bring them down to haskell and format them with, say, `formatTime defaultTimeLocale "%Y-%m-%d"` then i get "2017-04-15"

however, it i simply don't use my `truncateDate` function, then the exact same pipeline yield the "proper" date, "2017-04-16".

anyone have any idea what is happening here?

(this is in LTS-6.10, so it is esqueleto-2.4.3)

**Comment by Philonous** [comment]
Could this simply be a timezone problem? Note that `2017-04-16 00:00:00+10` is `2017-04-15 14:00:00+0` (UTC), whereas `2017-04-16 16:37:32.090688+10` is `2017-04-16 02:37:32.090688+0` (UTC)

**Comment by parsonsmatt** [comment]
OK, so as documented in the #180 PR, this is definitely a timezone issue.
