### ISSUE TITLE
esqueleto-3.5.0.0 generates malformed SQL when notIn is passed an empty list

### ISSUE THREAD

**Issue by cdparks** [bitemyapp/esqueleto#272]
An `notIn` expression using the legacy API:

```haskell
fetchUsersExcept :: MonadIO m => [Text] -> SqlReadT m [Entity User]
fetchUsersExcept names = select . from $ \users -> do
  where_ $ users ^. UserName `notIn` valList names
  pure users
```

or the experimental API:

```haskell
fetchUsersExcept :: MonadIO m => [Text] -> SqlReadT m [Entity User]
fetchUsersExcept names = select $ do
  users <- from $ table @User
  where_ $ users ^. UserName `notIn` valList names
  pure users
```

will generate a malformed SQL query when passed an empty list:

```haskell
fetchUsersExcept []
```

=>

```plaintext
[Debug#SQL]
SELECT "users"."id", "users"."name"
FROM "users"
WHERE "users"."name" NOT IN (); []
esqueleto-bug: SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \")\"", sqlErrorDetail = "", sqlErrorHint = ""}
```

Apparently Postgres (I'm using 10.14) doesn't like `x NOT IN ()`. Sqlite seems to accept this syntax.

It looks to me like `esqueleto` [protects against passing an empty list](https://github.com/bitemyapp/esqueleto/blob/3a12a15d0084877833d1ff2d36d94e1d47587e4b/src/Database/Esqueleto/Internal/Internal.hs#L931) for `in_`, but not for `notIn`. This seems like a behavior change based on [this older commit](https://github.com/bitemyapp/esqueleto/blob/e39c62990e0854e655e55e2ef6f874641efa26cc/src/Database/Esqueleto/Internal/Internal.hs#L949), which used a helper function [`ifNotEmptyList`](https://github.com/bitemyapp/esqueleto/blob/e39c62990e0854e655e55e2ef6f874641efa26cc/src/Database/Esqueleto/Internal/Internal.hs#L2198).

I have [a repo](https://github.com/cdparks/esqueleto-bug) demonstrating this, but it's probably easiest to verify this in your own setup.

**Comment by belevy** [comment]
#273 fixes the issue
