### ISSUE TITLE
Missing Instances for `:&` - bug or feature?

### ISSUE THREAD

**Issue by m4dc4p** [bitemyapp/esqueleto#290]
In writing some queries, I've found a need for `ToAlias`/`ToAliasReference`/`SqlSelect` instances for the `:&` type. There are already instances of those classes for `(,)`, `(,,)`, and so on, and `:&` doesn't really seem any different.

Is this an oversight or is there some reason those instances aren't defined for `:&`?

Thanks!

(I'm using 3.4.2.1 so please let me know if I just need to upgrade).

**Comment by parsonsmatt** [comment]
Definitely a bug/oversight if we're supporting `(,,)` in places but not `:&`

There's a `SqlSelect` instance in a new version

**Comment by m4dc4p** [comment]
Much appreciated!

**Comment by parsonsmatt** [comment]
We should still implement `ToAlias` and `ToAliasReference`, I think :)

**Comment by m4dc4p** [comment]
My PR is up but needs approval to run CI on it.

**Comment by m4dc4p** [comment]
Thanks for accepting this one!
