### ISSUE TITLE
Ambiguous column reference when using union result in subquery/CTE with persistent-postgresql

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#299]
@mauriciofierrom posted [this issue in `persistent`](https://github.com/yesodweb/persistent/issues/1363), but I think it belongs here.

Copying:

> ### Description
> With the `persistent-postgresql` library, when using the result of a `union_` in a subquery/CTE, the generated SQL repeats the "v" alias, resulting in an error about an ambiguous column reference. The generated SQL for the `persistent-sqlite` backend worked fine.
> 
> ### Envrironment
> Here's the [gist](https://gist.github.com/mauriciofierrom/da37b32c54aa4a6a3e67c588304b4d8e) with the result of running the relevant commands listed in the issue template.
> 
> ### Script
> Here's the [script](https://gist.github.com/mauriciofierrom/6803e44e5354b04b7be89c56707df067) that results in the exception.
> 
> If considered relevant I'd like to work on this and if that would be OK, any guidance would be highly appreciated.

**Comment by parsonsmatt** [comment]
@mauriciofierrom can you post the generated SQL from `sqlite` and `postgresql`?

**Comment by mauriciofierrom** [comment]
@parsonsmatt sorry for the confusion! I'll add the generated SQL to the description. Thanks for copying it!

**Comment by parsonsmatt** [comment]
Ok, cool, so it's the same generated SQL, but `sqlite` is more permissive about what it is accepting.

Hmm! This is interesting. I'm guessing the thing-to-do here is in the call to `union_` to grab the `IdentState` and ensure that the second query carries on from the end of the first query. This happens in `Database.Esqueleto.Experimental.From.SqlSetOperation`:

```haskell
instance (ToSqlSetOperation a c, ToSqlSetOperation b c, res ~ SqlSetOperation c)
  => Union_ (a -> b -> res) where
    union_ = mkSetOperation " UNION "

-- | Helper function for defining set operations
-- @since 3.5.0.0
mkSetOperation :: (ToSqlSetOperation a a', ToSqlSetOperation b a')
               => TLB.Builder -> a -> b -> SqlSetOperation a'
mkSetOperation operation lhs rhs = SqlSetOperation $ \p -> do
    (leftValue, leftClause) <- unSqlSetOperation (toSqlSetOperation lhs) p
    (_, rightClause) <- unSqlSetOperation (toSqlSetOperation rhs) p
    pure (leftValue, \info -> leftClause info <> (operation, mempty) <> rightClause info)

instance (SqlSelect a r, ToAlias a, ToAliasReference a) => ToSqlSetOperation (SqlQuery a) a where
    toSqlSetOperation subquery =
        SqlSetOperation $ \p -> do
            (ret, sideData) <- Q $ W.censor (\_ -> mempty) $ W.listen $ unQ subquery
            state <- Q $ lift S.get
            aliasedValue <- toAlias ret
            Q $ lift $ S.put state
            let aliasedQuery = Q $ W.WriterT $ pure (aliasedValue, sideData)
            let p' =
                  case p of
                    Parens -> Parens
                    Never ->
                      if (sdLimitClause sideData) /= mempty
                          || length (sdOrderByClause sideData) > 0 then
                        Parens
                      else
                        Never
            pure (aliasedValue, \info -> first (parensM p') $ toRawSql SELECT info aliasedQuery)
```

I suspect this last bit of code is the source of the error.

**Comment by belevy** [comment]
I think I explicitly wanted it to repeat. Just remove the call to get/put and it shouldnt repeat.

**Comment by belevy** [comment]
That said, this is a different code path. You are looking at union in general rather than the recursive CTE path.

**Comment by belevy** [comment]
Actually nevermind I misread the query. Carry on.

**Comment by belevy** [comment]
So the issue appears to be selecting from a subquery that returns an aliased value isn't re-aliasing it to ensure consistent naming.

**Comment by dsh** [comment]
When I hit this bug removing the union eliminated the ambiguous column error, so I think the union probably is required.
