### ISSUE TITLE
Incorrect SQL query generated for PostgreSQL.upsert

### ISSUE THREAD

**Issue by gromakovsky** [bitemyapp/esqueleto#300]
I tried using [upsert](https://hackage.haskell.org/package/esqueleto-3.5.3.0/docs/Database-Esqueleto-PostgreSQL.html#v:upsert) function trying to produce `INSERT INTO ... VALUES ... ON CONFLICT DO NOTHING`. I passed an empty list of updates and got:
> SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"WHERE\"", sqlErrorDetail = "", sqlErrorHint = ""}

I looked at logs and noticed that the following SQL statement is generated:
> INSERT INTO “foo_table”(“foo_id”,“foo_bar_id”,“foo_type”) VALUES ... ON CONFLICT (“foo_id”,“foo_bar_id”) DO UPDATE SET  WHERE “foo_table”.“foo_id” =... RETURNING ...`

As far as I understand, it is invalid because there is nothing between SET and WHERE. I think it would be more correct to produce `DO NOTHING` instead of `UPDATE SET WHERE...` in this case. Note that [insertSelectWithConflictCount](https://hackage.haskell.org/package/esqueleto-3.5.3.0/docs/src/Database.Esqueleto.PostgreSQL.html#insertSelectWithConflictCount) seems to handle this case correctly.

**Comment by parsonsmatt** [comment]
Hm. This is really a `persistent-postgresql` problem, since we call `upsertSql` on the `SqlBackend` given by `persistent-postgresql`, which does not check for an `updateSql` of `""`.

I think I can work up a patch for this. Going to check for an empty list of updates, and if so, we'll do a tet replace of `DO UPDATE SET WHERE` to `DO NOTHING WHERE`.

**Comment by parsonsmatt** [comment]
Oh, that won't work. We can't do a `WHERE` if it's a `DO NOTHING` lol. Even easier.

**Comment by gromakovsky** [comment]
@parsonsmatt oh, thanks for such a quick fix 😊 
I have tested it in my code and can confirm that it works as expected now (at least in my case) 👍

**Comment by parsonsmatt** [comment]
The code in my PR will break if nothing is inserted. I'd recommend using something else

**Comment by parsonsmatt** [comment]
Fixed by #301
