### ISSUE TITLE
Safely coercing newtype'd Values

### ISSUE THREAD

**Issue by EggBaconAndSpam** [bitemyapp/esqueleto#302]
Hi all!

I'm struggling with using Esqueleto in the presence of an abundance of newtype wrappers, where the only way out is to use `veryUnsafeCoerceSqlExprValue` from `Database.Esqueleto.Internal.Internal` (which is both ugly and indeed potentially unsafe).

I therefore propose:
```
cast :: Coercible a b => SqlExpr (Value a) -> SqlExpr (Value b)
cast = veryUnsafeCoerceSqlExprValue
```
which would complement the existing
```
castString :: (SqlString s, SqlString r) => SqlExpr (Value s) -> SqlExpr (Value r) 
castNum :: (Num a, Num b) => SqlExpr (Value a) -> SqlExpr (Value b) 
```

Does anyone see a reason why lifting the coercibility of newtypes to sql expressions should be a bad idea?

**Comment by EggBaconAndSpam** [comment]
Now that I've written this I realise that just because two types may have the same runtime representation in Haskell doesn't mean that they share the same SQL representation. So this really wouldn't be much safer than just coercing arbitrary types 😞

**Comment by dnikolovv** [comment]
@EggBaconAndSpam  You do have access to the sql representation through `PersistFieldSql` though.

**Comment by dnikolovv** [comment]
@parsonsmatt That seems like a decent solution.

The problem originated when we were trying to write an `on` clause similar to this:

```haskell
newtype SomeId = SomeId UUID
newtype SomeOtherId = SomeOtherId UUID

select $ from $ \something `LeftOuterJoin` anotherThing -> do
  on $ anotherThing ?. SomeIdField ==. something ^. SomeIdField
```

**Comment by parsonsmatt** [comment]
Oh, yeah, a `AsSqlUUID` class is what I'd write for that, probably

If those are `persistent` `Key` types, then you can use the `ToBaseId` class

**Comment by dnikolovv** [comment]
:bow:

**Comment by Qqwy** [comment]
In our project we ended up doing

```
sqlRawX :: Esq.SqlExpr (Esq.Value TheNewtype) -> Esq.SqlExpr (Esq.Value TheUnderlyingType)
sqlRawX =
  Control.Exception.assert (Esq.sqlType (Proxy :: Proxy TheNewtype) == Esq.sqlType (Proxy :: Proxy TheUnderlyingType))
    Esq.veryUnsafeCoerceSqlExprValue
```

Such an assert could of course also be added to the definition of `safeCast` in @parsonsmatt 's example above.

The only way to make this truly type-safe rather than relying on a runtime assert is if there were a way to check the SQL type at compile-time. But that probably requires a change of `sqlType` from the land of runtime functions to the land of associated type families.
