### ISSUE TITLE
Make subqueries more flexible (e.g. allow to join on subquery)

### ISSUE THREAD

**Issue by mb21** [bitemyapp/esqueleto#32]
As I've [asked on Stackoverflow](https://stackoverflow.com/questions/45057213/esqueleto-join-on-subquery-using-sublist-select):

I'm trying to translate the following SQL to Esqueleto:

	SELECT id, task_id, author_id
	FROM scenario
	INNER JOIN ( SELECT task_id as tId, author_id as aId, MAX(last_update) as lastUp
	    	     FROM scenario
		         GROUP BY task_id, author_id
		       ) t
	      ON task_id = tId AND author_id = aId AND last_update = lastUp

To do a sub-query, you have to use [subList_select](https://www.stackage.org/haddock/lts-8.22/esqueleto-2.5.3/Database-Esqueleto.html#v:subList_select).

I couldn't figure out a way to combine it with the pattern matching in:

    from $ \(s `InnerJoin` ?subQueryhere?) -> do ...

So I tried with `where_` instead:

    where_ (s ^. ScenarioTaskId ==. (subList_select $
             from $ \s' -> do
             groupBy (s' ^. ScenarioTaskId, s' ^. ScenarioAuthorId)
             return s'
           ) ^. ScenarioTaskId)

However, this doesn't compile since `subList_select` returns a `expr (ValueList a)` instead of a `expr (Entity Scenario)`.

**Comment by mb21** [comment]
I guess I can use the following which should be semantically identical (inspired by [this answer](https://stackoverflow.com/a/123481/214446)):

    $ select
    $ from $ \( s `LeftOuterJoin` ms ) -> do
            on ( just (s ^. ScenarioAuthorId)  ==. ms ?. ScenarioAuthorId &&.
                 just (s ^. ScenarioTaskId)    ==. ms ?. ScenarioTaskId   &&.
                 just (s ^. ScenarioLastUpdate) <. ms ?. ScenarioLastUpdate )
      where_ (isNothing (ms ?. ScenarioId))

But if in the future Esqueleto could support more flexible sub-queries with multiple results (not only in combination with `in_` etc.), that would be great.

**Comment by parsonsmatt** [comment]
Fixed by #172
