### ISSUE TITLE
Accommodate database specific behavior in Esqueleto

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#33]
Made the branch splitsqueleto for this.

https://github.com/prowdsponsor/esqueleto/issues/32 is a good example of the problem. Because of the way SqlExpr is structured, I don't think I can even fix this with an unsafe function without adding a new constructor to SqlExpr. I'd rather fix this properly anyway.

My options, as I see them are:

1. Move out of Esqueleto any operation which isn't uniform across the supported databases. I care principally about PostgreSQL and MySQL right now. This would mean creating a new database-specific typeclass.

2. Leave Esqueleto intact, remove the Esqueleto instance for `SqlExpr`, make newtypes specific to the databases in question.

Brain's run out of steam but I am certain I am missing some alternatives with good safety and composability.

One thing that stands out to me is that `random()` and `rand()` are not just usable under an `ORDER BY` but also in `select`: 

```
mysql> select RAND();
+---------------------+
| RAND()              |
+---------------------+
| 0.20325268451427358 |
+---------------------+
1 row in set (0.00 sec)

mysql> ^DBye
[ callen@chalcis ~/work ✔ ]
$ sudo -u postgres psql 
psql (9.5.7)
Type "help" for help.

postgres=# select random();
      random       
-------------------
 0.100939188618213
(1 row)

postgres=# 
```

**Comment by bitemyapp** [comment]
Solid question from @cdparks

>>Move out of Esqueleto any operation which isn't uniform across the supported databases
>Do you know how many currently supported operations would be affected here?

I don't think I can drum all these up at once, so I'm not going to commit to a one-time change. The expectation is that people will _always_ be using a database specific constraint and so the strengthening of a constraint should not matter.

I'll break out the options a little more modularly:

1. Database-specific typeclasses extending Esqueleto
2. Database-specific SQLExpr types (could be newtype, could be entirely new)

1, 2, or (1, 2) could be done to solve this problem.

**Comment by parsonsmatt** [comment]
It seems like we've settled on the least complex and "least safe" answer of "put database specific stuff in database specific modules." If you import `Database.Esqueleto.PostgreSQL` and expect it to work with MySQL, then that's a user-error that's unsupported.
