### ISSUE TITLE
Add: BETWEEN

### ISSUE THREAD

**Issue by ricksanchez** [bitemyapp/esqueleto#34]
What is your opinion about adding BETWEEN ... AND ...?
I find this feature useful while writing SQL, but esqueleto lacks it.

**Comment by bitemyapp** [comment]
I'd need to know more about it, which databases support this?

**Comment by ricksanchez** [comment]
well, at least postgres, oracle, sql server and even mysql, probably it is a part of an old sql standard ( I cannot find a reference in the sql 92)

**Comment by ibarrae** [comment]
I would like to take this issue if that's ok @parsonsmatt

**Comment by parsonsmatt** [comment]
heck yeah! Go for it @ibarrae :) Please post any questions you have.
