### ISSUE TITLE
`deriveEsqueletoRecord` should generate a `ToMaybe` instance

### ISSUE THREAD

**Issue by evanrelf** [bitemyapp/esqueleto#344]
For example, if I have this data type:

```haskell
data Person = Person
  { name :: Text
  , age :: Natural
  }
```

If I invoke [`deriveEsqueletoRecord`](https://hackage.haskell.org/package/esqueleto-3.5.8.1/docs/Database-Esqueleto-Record.html#v:deriveEsqueletoRecord), I'll get a new `SqlPerson` data type, but it's missing a `ToMaybe` instance, which seems to be necessary for using the type in left joins.

**Comment by parsonsmatt** [comment]
This was fixed in 3.5.13.1
