### ISSUE TITLE
Reexport From in Database.Esqueleto

### ISSUE THREAD

**Issue by ricksanchez** [bitemyapp/esqueleto#35]
I found very useful to use something like
```
verytypicaltableandjoins :: ... (From query expr backend ...
verytypicaltableandjoins othertable = from ...
```
and this needs a type signature because it is at the top level, right now I have to import the `Database.Esqueleto.Internal.Language` and that is a bit too awful.

This enables me to keep DRY more code.
Could this be useful for other people as well?

**Comment by bitemyapp** [comment]
Slightly orthogonal but have you tried https://github.com/frontrowed/dovetail for simple joins at all?

**Comment by bitemyapp** [comment]
It's in `HEAD` now.

**Comment by ricksanchez** [comment]
Thank you for exporitng it.
I was not aware of that project. I will take a look.
