### ISSUE TITLE
Natural keys are totally broken

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#36]
A natural key is a primary key on an attribute of a model that is assumed to be unique. A composite key is a key consisting of multiple columns. Persistent does not have a way to define a natural `Primary` key -- these are assumed to be composite keys.

Reported in [`persistent`](https://github.com/yesodweb/persistent/issues/685) as well.

Given this entity definition:

```
User
    name Text

    Primary name
```

calling `hasCompositeKey (entityDef (Nothing :: Maybe User))` will return `True` even though the key is *not* composite: it's a single field.

Using

```
User
    Id Text sql=name
```

Is not the same, because I can't specify the `Id` of an entity before inserting it -- it's not part of the `User`, it's part of `Entity User`.

**Comment by parsonsmatt** [comment]
[This is the function that is triggering the error](https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto/Internal/Sql.hs#L639-L663). The error that is rendered is:

```
unsafeSqlBinOpComposite: cannot deconstruct ("?",[PersistText "4-114-4125971-0773856"]).
```

It determines to use `ECompositeKey` in [the definition of[`(^.)`](https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto/Internal/Sql.hs#L423-L432).

It may be possible to fix this by considering a composite key with a single field. Perhaps [this function](https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto/Internal/Sql.hs#L647-L650) could be rewrittten like:

```haskell
deconstruct :: (TLB.Builder, [PersistValue]) -> ([TLB.Builder], [PersistValue])
deconstruct ("?", [PersistList vals]) = (replicate (length vals) "?", vals)
deconstruct ("?", [x]) = (["?"], [x])
deconstruct (b', []) = (TLB.fromLazyText <$> TL.splitOn "," (TLB.toLazyText b'), [])
deconstruct x = err $ "cannot deconstruct " ++ show x ++ "."
```

though I don't know the effect this would have on other cases.

**Comment by bitemyapp** [comment]
`HEAD` has this rectified now, thank you!

**Comment by felixSchl** [comment]
Are you sure this is fixed? After updating the only that changed in my case is the error message: `SqlBinOpCompositeErr DeconstructionError`.

**Comment by bitemyapp** [comment]
>Are you sure this is fixed?

Not in the slightest. By all means introducing a breaking test in a PR if you have one.

I've mostly planned on keeping the lights on on Esqueleto until I can carve out time for a rewrite with https://github.com/bitemyapp/bluetick

I'll fix and merge whatever I can meanwhile, though.

**Comment by felixSchl** [comment]
Alright I will prepare such a PR. On a side note, have you detailed your reasons for attempting a rewrite somewhere? I find Esqueleto quite pleasant to work with as it gives me the best of both words: type safety and good control over my queries. It also has a lightweight DSL and is easy on the types as opposed to some other libraries. And it integrates with persistent, and the list goes on. It will be interesting to see why you are contemplating a rewrite :)

**Comment by bitemyapp** [comment]
@felixSchl I'm not sure why you think a rewrite would give any of that up. The point is to make it more reliable, purge the partiality from the API, make it simpler, and make it more maintainable. I don't want to change much else.

**Comment by felixSchl** [comment]
That's awesome :) I guess I was thinking that because it's not even called Esqueleto anymore. Wouldn't it be strange to have two packages export the same module and function names? Anyway, I was just curious, really.

I was looking at using bloodhound for a project I am currently working on but haven't had the chance to yet, unfortunately.

**Comment by bitemyapp** [comment]
I'll try to make it as similar to Esqueleto as I can, but I don't hold out a ton of hope that I can make it a zero-code-change migration.
