### ISSUE TITLE
Specific error types

### ISSUE THREAD

**Issue by parsonsmatt** [bitemyapp/esqueleto#37]
When `esqueleto` errors, it `error`s. It seems like a very nice quick fix would be to purely throw a real exception type with context rather than stringly typed errors.

**Comment by FintanH** [comment]
I did a search for `error` in this repository but I could only see one case of it happening in code. Is it being propagated from Persistent, or am I missing something here?

**Comment by bitemyapp** [comment]
```
    deconstruct :: (TLB.Builder, [PersistValue]) -> ([TLB.Builder], [PersistValue])
    deconstruct ("?", [PersistList vals]) = (replicate (length vals) "?", vals)
    deconstruct ("?", [x]) = (["?"], [x])
    deconstruct (b', []) = (TLB.fromLazyText <$> TL.splitOn "," (TLB.toLazyText b'), [])
    deconstruct x = err $ "cannot deconstruct " ++ show x ++ "."
```

is an example of something that was previously partial (I just fixed an issue in it in the `mysql-rand` branch)

It uses `err` but it was previously implicitly spitting a bottom.

The problem with purging `error` is that `SqlExpr` isn't a `Monad` and doesn't really have a way to express "error". `SqlQuery` could possibly have an `ExceptT` slapped on top but that's a lot of annoying, ugly work.

@FintanH given that, upon reflection, I don't think this is a good ticket to pick up. I should've thought of these problems.

**Comment by FintanH** [comment]
Fair enough, maybe I'll check back in on taking it up if no one else has at a later point.

**Comment by parsonsmatt** [comment]
I see it on a bunch of places:

```
src/Database/Esqueleto/Internal/Sql.hs
147:-- unmatched 'OnClause's data on error.  Returns a list without
241:          go [] = error "Esqueleto/Sql/newIdentFor: never here"
451:  not_ (ECompositeKey _) = unexpectedCompositeKeyError "not_"
517:  (<#) _ (ECompositeKey _) = unexpectedCompositeKeyError "(<#)"
523:  (EInsert _ _) <&> (ECompositeKey _) = unexpectedCompositeKeyError "(<&>)"
581:    mapWhen []    _    = error "unsafeSqlCase: empty when list."
589:    foldHelp _ _ _ = unexpectedCompositeKeyError "unsafeSqlCase/foldHelp"
590:unsafeSqlCase _ (ECompositeKey _) = unexpectedCompositeKeyError "unsafeSqlCase"
612:unsafeSqlBinOp _ _ _ = unexpectedCompositeKeyError "unsafeSqlBinOp"
663:    err = error . ("unsafeSqlBinOpComposite: " ++)
743:  error "veryUnsafeCoerceSqlExprValueList: empty list."
773:          Just (Left err) -> liftIO $ throwIO $ PersistMarshalError err
1058:    mk _ (OnClause _) = error "Esqueleto/Sql/makeFrom: never here (is collectOnClauses working?)"
1074:    makeOnClause (ECompositeKey _) = unexpectedCompositeKeyError "makeFrom/makeOnClause"
1080:    mkExc (ECompositeKey _) = unexpectedCompositeKeyError "makeFrom/mkExc"
1082:unexpectedCompositeKeyError :: String -> a
1083:unexpectedCompositeKeyError w = error $ w ++ ": non-id/composite keys not expected here"
1091:    mk (SetClause (ECompositeKey _)) = unexpectedCompositeKeyError "makeSet" -- FIXME
1096:makeWhere _    (Where (ECompositeKey _)) = unexpectedCompositeKeyError "makeWhere"
1113:makeHaving _    (Where (ECompositeKey _)) = unexpectedCompositeKeyError "makeHaving"
1175:  sqlInsertInto = error "Type does not support sqlInsertInto."
1189:  sqlSelectProcessRow = const (Right (error msg))
```

(note that `unexpectedCompositeKeyError` is calling `error`)

For the scope of this ticket, I'd honestly just expect to see `error` replaced with `Control.Exception.throw :: Exception e => e -> a` along with a sufficiently reasonable `EsqueletoProblem` type.

**Comment by bitemyapp** [comment]
@parsonsmatt oh I see, you don't mind if it's not `m a`, in that case, should be fine @FintanH

**Comment by FintanH** [comment]
Alright @bitemyapp I'll take a look around when I get more time and if I can do it I'll assign myself 😄

**Comment by FintanH** [comment]
@parsonsmatt @bitemyapp I gave this a crack and wanted to get your input on the code. Is this what you were mentioning above?
Error type here: https://github.com/FintanH/esqueleto/blob/errors/src/Database/Esqueleto/Internal/Sql.hs#L80-L85

Example use here:
https://github.com/FintanH/esqueleto/blob/errors/src/Database/Esqueleto/Internal/Sql.hs#L1095-L1099

**Comment by bitemyapp** [comment]
@FintanH ignore what I said before.

Looks good so far, some suggested modifications (you don't have to do this, I can do this after your PR if you like):

EsqueletoProblem -> EsqueletoError

I know the original code used strings, but I would lift those into a sum type so that people can pattern-match on whether it was due to a Not clause or whatever and know whether they've handled all errors. I can look into it after merging a PR of what you've done so far if you like.

**Comment by FintanH** [comment]
@bitemyapp Sounds good to me. No worries, I'll work on it and do a PR. Just to clarify, should I add more enumerations to account for each case?

e.g. 
https://github.com/FintanH/esqueleto/blob/errors/src/Database/Esqueleto/Internal/Sql.hs#L256
would be: NewIdentForError

https://github.com/FintanH/esqueleto/blob/errors/src/Database/Esqueleto/Internal/Sql.hs#L466
would be: CompositeKeyErrorNot

**Comment by bitemyapp** [comment]
@FintanH Sounds fine, although I can't be sure what'll work most nicely for the structure of the error type. I meant for a nested structure, CompositeKey that takes an argument of another sum type, so the inhabitants of the CompositeKey argument type don't need to mention composite key, etc.

**Comment by FintanH** [comment]
@bitemyapp Makes sense! Cool I'll work on it :)
