### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by tillydray** [bitemyapp/esqueleto#374]
There's a typo in [README#Experimental/New Joins](https://github.com/bitemyapp/esqueleto#experimentalnew-joins)

> The ON clause lambda will ___ all the available tables in it. This forbids runtime errors where an ON clause refers to a table that isn't in scope yet.

I'm not sure what fits there otherwise I'd make a PR

**Comment by isomorpheme** [comment]
I think I have an idea of what fits there so I opened #380; if it's not accurate then reviewers can always point that out of course.
