### ISSUE TITLE
Consider adding now() as a SqlExpr

### ISSUE THREAD

**Issue by iand675** [bitemyapp/esqueleto#38]
I'm not sure if this is PostgreSQL-specific or if `now` is used in other databases, but it's handy for setting updated_at fields and so forth:

```
now :: SqlExpr (Database.Esqueleto.Value UTCTime)
now = unsafeSqlFunction "now" ([] :: [SqlExpr (Database.Esqueleto.Value ())])
```

**Comment by FintanH** [comment]
I'm looking at how this is done via other SQL functions located in `src/Database/Esqueleto/Internal/Sql.hs` 

So I can see there are type constraints that stop the user from picking silly types for the `Value` for e.g.
```
random_  :: (PersistField a, Num a) => expr (Value a)
round_   :: (PersistField a, Num a, PersistField b, Num b) => expr (Value a) -> expr (Value b)
```

I was wondering is there a typeclass that would encapsulate the same idea for Time as `Num` is doing in the above?

**Comment by FintanH** [comment]
I have one solution that looks like:
`now_ :: (PersistField a, a ~ UTCTime) => expr (Value a)`

Thoughts on this?

**Comment by bitemyapp** [comment]
Is there a reason `now :: SqlExpr (Database.Esqueleto.Value UTCTime)` wouldn't work?

**Comment by FintanH** [comment]
I was adding it as `now_` to the `Esqueleto` class and it `expr` isn't made concrete to `SqlExpr` at that point

**Comment by FintanH** [comment]
You can compare the changes here: https://github.com/FintanH/esqueleto/tree/now

**Comment by bitemyapp** [comment]
@FintanH Adding it to the class is a more serious change than adding it as a separate helper function. I don't think this works uniformly on SQLite, MySQL, and PostgreSQL. There are some compatibility issues already (my fight with `rand_/random_` is a good example) but I don't want to compound the problem.

Taking a glance, here's what I got on PostgreSQL:

```
postgres=# select now();
              now              
-------------------------------
 2017-08-02 10:44:37.449892-05
(1 row)
```

Then MySQL:

```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2017-08-02 10:44:23 |
+---------------------+
1 row in set (0.01 sec)
```

SQLite didn't seem to work:

```
sqlite> select now();
Error: no such function: now
```

The default in the documentation looks like:

```
sqlite> SELECT date('now');
2017-08-02
```

You have to give SQLite a format string to get a result that looks more like MySQL and PostgreSQL.

So one concern right off the bat is that even if we're fine with `now_` only working for MySQL and PGSQL, we should test that the UTCTime `PersistField` parsing works with both formats. A straight-forward test that runs under the PGSQL and MySQL suite should work for this. I think @iand675 (correct me if I'm wrong) is using PostgreSQL so shoving this function out to the `PostgreSQL` module should be an acceptable resolution to this problem until I work out a re-design that better handles compatibility issues.

Feel free to ping me on Slack if you want to hammer this out more efficiently than Github thread ping-pong.

**Comment by mmzx** [comment]
Just a possible shortcut which has not been mentioned in the thread yet regarding sqlite:
select datetime('now'); 2017-08-02 16:10:47
Best, mAkos

**Comment by bitemyapp** [comment]
@iand675 could please you let me know if this sorts you out? https://github.com/bitemyapp/esqueleto/pull/46

**Comment by iand675** [comment]
It looks like it should!
