### ISSUE TITLE
use deleteCascade/deleteCascadeWhere with esqueleto?

### ISSUE THREAD

**Issue by tippenein** [bitemyapp/esqueleto#39]
Porting this issue from the [old repo](https://github.com/prowdsponsor/esqueleto/issues/147) 

See https://stackoverflow.com/questions/38999557/is-it-possible-to-use-deletecascade-with-esqueleto?noredirect=1#comment65358492_38999557

Is there a way to use deleteCascade/deleteCascadeWhere with esqueleto?

**Comment by bitemyapp** [comment]
There's nothing in place for it, but it could be added I think.

**Comment by tippenein** [comment]
Like mentioned in the SO comments, `PersistentImport.hs` includes `deleteCascade` but not `deleteCascadeWhere`
https://github.com/bitemyapp/esqueleto/blob/master/src/Database/Esqueleto/Internal/PersistentImport.hs#L10

This is how I would expect to interact with it in esqueleto:
```
deleteCascade $ from \p -> do
    where_ (p ^. PersonId ==. (toSqlKey 1))
```

**Comment by bitemyapp** [comment]
@tippenein `deleteCascade` just takes a key and generations a DB action that does a cascading delete. Esqueleto would need to make a custom action that looks something like:

```haskell
deleteCascade :: MonadIO m => SqlQuery () -> SqlWriteT m ()
```

I'm open to it, but I rarely delete (let alone cascading delete) in production so I'm not going to go out of my way for it for now.

**Comment by parsonsmatt** [comment]
I think what we "really" need here is a better way to set cascade behavior on the `persistent`. The issues [#910](https://github.com/yesodweb/persistent/issues/910) and [#999](https://github.com/yesodweb/persistent/issues/999) document this and the PR [#1056](https://github.com/yesodweb/persistent/pull/1056) implements it.

**Comment by parsonsmatt** [comment]
Closing since `persistent` supports proper cascade behavior
