### ISSUE TITLE
WITH+UPDATE / UPDATE FROM in PostgreSQL?

### ISSUE THREAD

**Issue by Mr-Andersen** [bitemyapp/esqueleto#396]
PostgreSQL supports `WITH` and `FROM` in `UPDATE` queries ([src](https://www.postgresql.org/docs/current/sql-update.html)). Esqueleto doesn't seem to support constructing such queries?

**Comment by parsonsmatt** [comment]
Yes, that's correct. There's a big ticket for making a postgres specific `update` here: https://github.com/bitemyapp/esqueleto/issues/306
