### ISSUE TITLE
Make examples for the README buildable

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#4]
Probably via an `examples` dir that's part of the build. Maybe worth having teeny-tiny tests/asserts so that the testing stuff doesn't overwhelm the important bits with noise.

Derived from #1

**Comment by bitemyapp** [comment]
https://github.com/bitemyapp/bloodhound/tree/master/examples is a good example to riff off of.

**Comment by alexeyzab** [comment]
Hi there! 

I would like to add this as one of the issues for the upcoming [Haskell Weekly's](https://github.com/haskellweekly/haskellweekly.github.io) Call for Participation section. See discussion in [#75](https://github.com/haskellweekly/haskellweekly.github.io/issues/75).

These are the guidelines we'd like to stick to in the future:
* Ensure that your project has at least one open-source licence. (we've decided to not define the term "open-source" and it is left to your own interpretation).
* Ensure that the issue tracker for your project is publicly accessible.
* Create a new issue in your issue tracker and clearly describe the task. Also mention the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.
* If you have specific requirements for contributors (e.g., copyright waiver), it must be mentioned in the description of the task (preferably with a link to CONTRIBUTING.md).

Thank you!

**Comment by bitemyapp** [comment]
https://github.com/bitemyapp/esqueleto/blob/master/LICENSE is BSD3

>Ensure that the issue tracker for your project is publicly accessible.

Yep, hi.

>Create a new issue in your issue tracker and clearly describe the task. Also mention the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.

Labels are a good idea for this, I'll make them now.

>If you have specific requirements for contributors (e.g., copyright waiver), it must be mentioned in the description of the task (preferably with a link to CONTRIBUTING.md).

I've never formalized this, if you have an example/starter document I'll take a look at it and see if it fits. At a minimum I should probably mention that any work done on one version of the API should be done on the other version whenever possible.

**Comment by alexeyzab** [comment]
I think Rust's Hyper has a thorough [CONTRIBUTING.md](https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md) with several requirements. If that seems like an overkill, Rocket has  a [section in the README.md](https://github.com/SergioBenitez/Rocket#contributing) describing how to contribute.

**Comment by bitemyapp** [comment]
I've also added a new label "needs-discussion": https://github.com/bitemyapp/esqueleto/issues/31

This is for anything that has unresolved design questions, so a PR out of the blue would be riskier for that.

**Comment by FintanH** [comment]
Creating an examples section on my fork https://github.com/FintanH/esqueleto/tree/examples/examples. Needs some work to align it with the bloodhound style examples
