### ISSUE TITLE
Purge the CPP in the test suite

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#41]
Split into separate test suites, share whatever's common to all of them.

**Comment by FintanH** [comment]
You can assign this bad boy to me 👍

**Comment by bitemyapp** [comment]
@FintanH won't let me. Try assigning yourself?

![screenshot from 2017-08-08 17-00-14](https://user-images.githubusercontent.com/320177/29096552-0eaa6a08-7c5b-11e7-9afd-58f53d3a0c38.png)

**Comment by FintanH** [comment]
I can't see any option for me to assign :/ Meh, I'll just work on it. I STAKE MY CLAIM HERE 😄

**Comment by bitemyapp** [comment]
@FintanH added you as a collaborator, accept and check again?
