### ISSUE TITLE
Pushing towards Esqueleto 2.5 release

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#5]
As stated elsewhere, this repository includes the improvements Easley made for Persistent 2.5 compatibility.

Before pushing to 2.6 compatibility, I'd like to cut a release so that people have a desert island of 2.5 compat. I'm tagging people who've registered an interest in this library to solicit requests for what they'd like to get into the upcoming release.

/cc @jb55 @jdreaver @AKurilin @danpalmer @thomasjm

**Comment by bitemyapp** [comment]
Also the version line-up between Esqueleto and Persistent is unintentional on my part even if Lessa was doing it on purpose before.

**Comment by jdreaver** [comment]
I'm mainly concerned about compatibility with the latest versions of `persistent` and GHC 8. I think both of these have been addressed in open PRs against the old repo.

Thanks for taking this over by the way! :tada:

**Comment by thomasjm** [comment]
I'm just interested in compatibility, my usage is pretty basic at the moment. I'd like to see this package on one of the Stackage GHC 8 LTS releases. Super exited you're taking it over!

**Comment by ncaq** [comment]
I suffered big extra-deps, it cause long time travis ci build.
I thanks you to your great job!

**Comment by mrkkrp** [comment]
So when can we hope for a new release on Hackage?

**Comment by bitemyapp** [comment]
@mrkkrp I could do it soon, wanted to check around for any other potential changes people might want.

Seems like pseudonom's compat bump is enough.

**Comment by bitemyapp** [comment]
http://hackage.haskell.org/package/esqueleto-2.5.0 is live with Persistent 2.5 compatibility. I'll be moving towards Persistent 2.6 next.

**Comment by mrkkrp** [comment]
Would it be possible to start keeping `CHANGELOG.md` file for the project?

**Comment by bitemyapp** [comment]
@mrkkrp Going forward, sure.
