### ISSUE TITLE
Add helper for projecting nullable fields

### ISSUE THREAD

**Issue by bigs** [bitemyapp/esqueleto#61]
hey!

not sure if this is wanted, but in a project i'm working on i had need to construct expressions with values that could be null, guarding against their nullity with a `WHERE` clause. i've forked the project and contributed the functions to the `Esqueleto` class. if there's any interest in having this merge upstream, i'll add some tests and make a pr! thoughts?

**Comment by bitemyapp** [comment]
I've merged https://github.com/bitemyapp/esqueleto/pull/62

I'm interested in the class you're suggesting if you'd still like to upstream that.
