### ISSUE TITLE
stringAgg can return null, but the type doesn't indicate that

### ISSUE THREAD

**Issue by paf31** [bitemyapp/esqueleto#68]
The type of `stringAgg` is

```haskell
stringAgg 
  :: SqlString s
  => SqlExpr (Value s)
  -> SqlExpr (Value s)
  -> SqlExpr (Value s)
```

which can be specialized to `Text`, but selecting `string_agg(foo, bar)` from an empty record set `foo` results in `NULL`. I noticed the other aggregations return `Maybe`, forcing the user to deal with this explicitly. Should `stringAgg` do the same?

**Comment by bitemyapp** [comment]
PostgreSQL right? I'd say this merits a patch harmonizing it with the other aggregations, ideally with a test that breaks the current version.

**Comment by qrilka** [comment]
Imo this behavior is from SQL itself, i.e. not DB-specific
