### ISSUE TITLE
base version constraint needs to be bumped

### ISSUE THREAD

**Issue by ilovezfs** [bitemyapp/esqueleto#7]
Right now it's set at < 4.9, but the current version is `base-4.9.0.0/installed-4.9`. Is this restriction really needed still?

**Comment by bitemyapp** [comment]
Good question! I'll give 'er a poke tonight unless you beat me to it.

**Comment by ilovezfs** [comment]
@bitemyapp FWIW, it seems to be fine. I've adopted your fork in the Homebrew git-annex formula. All of the git-annex tests passed using your esqueleto fork + that constraint bumped. Here's the PR from earlier that has shipped (you're in production!):

https://github.com/Homebrew/homebrew-core/pull/8387/files

**Comment by bitemyapp** [comment]
I think after 4.9 will be 4.10 and not 5.0 but it's entirely possible I'm wrong about that. I think they're saving 5.x for a big break.

**Comment by mrkkrp** [comment]
Any progress on this?
