### ISSUE TITLE
`update` seemingly isn't compatible with `SqlWriteT`

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#73]
First step is to add some tests exercising the different DB monads with specific capabilities (read, write, all) in the test suite. Ideally there should be tests demonstrating:

- ~`SqlWriteT` fails for a database action performing a select (use the hspec "can fail to typecheck" helper)~ Write might be inclusive of read? I hadn't looked too closely at this stuff before. Thanks @jkachmar
- `SqlReadT` fails at compile-time for a database action performing an insert, delete, update, etc. (`should-not-typecheck` is probably best for this purpose)
- Read succeeds for the various `select` actions
- Write succeeds for the various modification actions

**Comment by bitemyapp** [comment]
Follow-up: `run` functions should have types like:

`ReaderT SqlReadBackend IO a -> IO a`

`SqlReadT` and SqlWriteT` seem intended for upstream library functions. I could be wrong, but that's what it seemed like from experimentation.

**Comment by parsonsmatt** [comment]
I believe this behavior is fixed now
