### ISSUE TITLE
Persistent 2.6 compatibility

### ISSUE THREAD

**Issue by bitemyapp** [bitemyapp/esqueleto#8]
Title. Fair warning, I don't care about Esqueleto and Persistent having matchy-matchy versioning.

**Comment by mrkkrp** [comment]
When can we expect persistent-2.6-compatible release? If you don't plan to work on this right now, I can try to allow 2.6 and see what breaks, then open a PR. It'd be nice to get 2.6-compatibility by next week (16 January), I'm ready to spend some time to make it happen, although it looks like no serious changes are necessary (according to persistent changelog, it should be enough to just bump upper bound).

**Comment by peti** [comment]
What about https://github.com/prowdsponsor/esqueleto/pull/149? That patch seems to work fine.

**Comment by bitemyapp** [comment]
It's possible we ate the cost of a compat break already for 2.5. I'm not sure if enolan's PR is based on the 2.5 variant I used in this repo.

I'm at a conf until the end of the week, so I can't investigate this just yet (I'd be foggy), but if someone starts kicking around a PR and tells me what breaks it'll definitely happen sooner.

**Comment by qrilka** [comment]
@bitemyapp any plans of a new release with this issue resolved?

**Comment by nd2s** [comment]
Would be good if there were a release very soon so it can finally be used with `lts-7.x`.

**Comment by bitemyapp** [comment]
![screenshot from 2017-01-22 12-55-39](https://cloud.githubusercontent.com/assets/320177/22184970/1625d696-e0a2-11e6-8e8d-69883664ec22.png)

**Comment by mrkkrp** [comment]
🎉 Now it can be enabled on Stackage.

**Comment by nd2s** [comment]
@bitemyapp Great - many thanks!

**Comment by peti** [comment]
@bitemyapp, how do you get your shell to add that little check-mark to the prompt for non-error exit codes? Is that `bash`?

**Comment by bitemyapp** [comment]
@peti that's not what it does, it's a dirty check for my Git repository so that I don't forget to check things in.

My entire dev env is and always has been public: github.com/bitemyapp/dotfiles
