### ISSUE TITLE
Support for persistent-2.8.1?

### ISSUE THREAD

**Issue by peti** [bitemyapp/esqueleto#80]
Current versions of Stackage have updated to version 2.8.x of the persistent library. Would it be possible to get a new release that supports those newer versions?

**Comment by bitemyapp** [comment]
Cf. https://github.com/bitemyapp/esqueleto/issues/78

It's possible, but my priority is on fixing the type-safety issues.

**Comment by clinty** [comment]
Any commit in particular?

**Comment by bitemyapp** [comment]
@clinty I didn't have one in particular in mind, did latest on `master` not work?

**Comment by clinty** [comment]
It seems to work.

**Comment by peti** [comment]
Will there be a new version that fixes this issue?

**Comment by parsonsmatt** [comment]
Closing as duplicate of #89 and #109
