### ISSUE TITLE
Provide a clean way to build arbitrarily large `groupBy`'s

### ISSUE THREAD

**Issue by tysonzero** [bitemyapp/esqueleto#81]
It's not uncommon to need to group on a fairly large number of things, and it's annoying to have things stop building suddenly when you create too big of a tuple, which you then have to start nesting.

I suggest a pair of combinators, one of which that has type `expr (Value a) -> expr (Value a) -> SomeValues` and another that has type `expr (Value a) -> SomeValues -> SomeValues` (where `SomeValues` can be anything that has a `ToSomeValues` instance). If we for example called them `<:` and `<#`, and made them `infixr`, you could then do `groupBy $ foo <: ... <: bar <# baz`.

**Comment by ibarrae** [comment]
What about if esqueleto provides the following instance?
``` haskell
instance ToSomeValues a => [a] where
  toSomeValues = fmap toSomeValues
```
Would that solve the issue/is it viable? cc./ @tysonzero @parsonsmatt

**Comment by parsonsmatt** [comment]
@ibarrae That would require all the values having the same type.

So, one way to work-around this, is to nest tuples. So if you've got:

```haskell
groupBy (e0, e1, e2, e3, e4, e5)
```

and that trips the limit, you can nest the tuples.

```haskell
groupBy ((e0, e1, e2, e3, e4), (e5, e6))
```

It might be nice to have an `HList` sort of thing, but I'd prefer to depend on a good `HList` implementation that's relatively well supported.

**Comment by parsonsmatt** [comment]
@tysonzero I've opened a PR that has some documentation improvements for `groupBy` that points out nesting tuples to get around this. Would you say this addresses this problem sufficiently?
